[package]
name = "riftphys-terrain"
version = "0.2.0"
edition = "2021"

[features]
image = ["dep:image"]

[dependencies]
riftphys-core = { path = "../riftphys-core" }
riftphys-materials = { path = "../riftphys-materials" }
riftphys-collision = { path = "../riftphys-collision" }
riftphys-geom = { path = "../riftphys-geom" }
glam = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"], optional = true }
