[package]
name = "riftphys_ffi"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
riftphys-world     = { path = "../riftphys-world" }
riftphys-core      = { path = "../riftphys-core" }
riftphys-geom      = { path = "../riftphys-geom" }
riftphys-materials = { path = "../riftphys-materials" }
riftphys-terrain = { path = "../riftphys-terrain" }
glam   = { workspace = true, default-features = false, features = ["std"] }
